/*
 * This source file was generated by the Gradle 'init' task
 */
package bankingapp;

import java.math.BigDecimal;

import bankingapp.model.*;

public class App {
    public static void main(String[] args) {
        Money initialdeposit = new Money(new BigDecimal(200), "dollars");
        Money overdraftlimit = new Money(new BigDecimal(100), "dollars");
        CheckingAccount c = new CheckingAccount(
            overdraftlimit, initialdeposit, "dollars");
        
        Money depositamnt = new Money(new BigDecimal(50), "dollars");
        c.deposit(depositamnt, "HELLO THERE I JUST PUT MONEY");
        SavingsAccount s = new SavingsAccount(
            initialdeposit, "dollars", new BigDecimal(2.0));
        Customer customer = new Customer.Builder("Bipin", "Bipin", "bipin@bipin.com").addAccount(s).addAccount(c).build();
        System.out.println(customer.toString());
    }
}
