/*
 * This source file was generated by the Gradle 'init' task
 */
package bankingapp;

import java.math.BigDecimal;

import bankingapp.model.*;

public class App {
    public static void main(String[] args) {
        Money initialdeposit = new Money(new BigDecimal(200), "dollars");
        Money overdraftlimit = new Money(new BigDecimal(100), "dollars");
        CheckingAccount c = new CheckingAccount(
            overdraftlimit, initialdeposit, "dollars");
        
        Money depositamnt = new Money(new BigDecimal(50), "dollars");
        c.deposit(depositamnt, "HELLO THERE I JUST PUT MONEY");
    }
}
