/*
 * This source file was generated by the Gradle 'init' task
 */
package bankingapp;

import java.math.BigDecimal;

import bankingapp.model.*;

public class App {
    public static void main(String[] args) {
        Money m = new Money(new BigDecimal("1e-12"), "dollars");
        System.out.println(m);
    }
}
