/*
 * This source file was generated by the Gradle 'init' task
 */
package bankingapp;

import org.junit.jupiter.api.Test;

import bankingapp.model.Money;

import static org.junit.jupiter.api.Assertions.*;

import java.math.BigDecimal;

class AppTest {

}
