/*
 * This source file was generated by the Gradle 'init' task
 */
package bankingapp;

import org.junit.jupiter.api.Test;

import bankingapp.model.Money;

import static org.junit.jupiter.api.Assertions.*;

import java.math.BigDecimal;

class AppTest {
    @Test void positiveMoney() {
        Money m = new Money(new BigDecimal(100), "dollars");
        assertEquals(m.toString(), "100 dollars");
    }
    @Test void negativeMoney(){
        assertThrows(IllegalArgumentException.class, ()->{
            new Money(new BigDecimal(-100), "dollars");
        });
    }
    @Test void zeroMoney(){
        Money m = new Money(new BigDecimal(0), "dollars");
        assertEquals(m.toString(), "0 dollars");
    }

}
