/*
 * This source file was generated by the Gradle 'init' task
 */
package bankingapp.model;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.math.BigDecimal;
import java.util.HashSet;

class MoneyTest {
    @Test void positiveMoney() {
        Money m = new Money(new BigDecimal(100), "dollars");
        assertEquals("100 dollars", m.toString());
    }
    @Test void negativeMoney(){
        assertThrows(IllegalArgumentException.class, ()->{
            new Money(new BigDecimal(-100), "dollars");
        });
    }
    @Test void zeroMoney(){
        Money m = new Money(new BigDecimal(0), "dollars");
        assertEquals("0 dollars", m.toString());
    }
    @Test void veryLargeMoney(){
        Money m = new Money(new BigDecimal("1e+12"), "dollars");
        System.out.println(m);
        assertEquals("1E+12 dollars", m.toString());
    }
    @Test void verySmallMoney(){
        Money m = new Money(new BigDecimal("1e-12"), "dollars");
        System.out.println(m);
        assertEquals("1E-12 dollars", m.toString());
    }
    @Test void addMoney(){
        Money m = new Money(new BigDecimal(100), "dollars");
        Money n = new Money(new BigDecimal(100), "dollars");
        assertEquals("200 dollars",  m.add(n).toString());
    }
    @Test void addMoneyDiffCurrency(){
        Money m = new Money(new BigDecimal(100), "dollars");
        Money n = new Money(new BigDecimal(100), "euros");
        assertThrows(IllegalArgumentException.class, () -> m.add(n));
    }
    @Test void subtractMoney(){
        Money m = new Money(new BigDecimal(100), "dollars");
        Money n = new Money(new BigDecimal(100), "dollars");
        assertEquals("0 dollars",  m.subtract(n).toString());
    }
    @Test void subtractMoneyDiffCurrency(){
        Money m = new Money(new BigDecimal(100), "dollars");
        Money n = new Money(new BigDecimal(100), "euros");
        assertThrows(IllegalArgumentException.class, () -> m.subtract(n));
    }
    @Test void subtractMoneyNegativeResult(){
        Money m = new Money(new BigDecimal(100), "dollars");
        Money n = new Money(new BigDecimal(200), "dollars");
        assertThrows(IllegalArgumentException.class, () -> m.subtract(n));
    }
    @Test void equalsMoney(){
        Money m = new Money(new BigDecimal(100), "dollars");
        Money n = new Money(new BigDecimal(100), "dollars");
        assertEquals(true,  m.equals(n));
    }
    @Test void equalsMoneyFalse(){
        Money m = new Money(new BigDecimal(100), "dollars");
        Money n = new Money(new BigDecimal(200), "dollars");
        assertEquals(false,  m.equals(n));
    }
    @Test void equalsMoneyDiffCurrency(){
        Money m = new Money(new BigDecimal(100), "dollars");
        Money n = new Money(new BigDecimal(200), "euros");
        assertThrows(IllegalArgumentException.class, () -> m.equals(n));
    }
    @Test void compareMoney(){
        Money m = new Money(new BigDecimal(100), "dollars");
        Money n = new Money(new BigDecimal(100), "dollars");
        assertEquals(0,  m.compareTo(n));
    }
    @Test void compareMoneyDiffCurrency(){
        Money m = new Money(new BigDecimal(100), "dollars");
        Money n = new Money(new BigDecimal(100), "euro");
        assertThrows(IllegalArgumentException.class, () -> m.compareTo(n));
    }
    @Test void compareMoneyNegativeDifference(){
        Money m = new Money(new BigDecimal(150), "dollars");
        Money n = new Money(new BigDecimal(210), "dollars");
        assertEquals(true,  m.compareTo(n) < 0);
    }
    @Test void compareMoneyPositiveDifference(){
        Money m = new Money(new BigDecimal(100), "dollars");
        Money n = new Money(new BigDecimal(30), "dollars");
        assertEquals(true,  m.compareTo(n) > 0);
    }
    @Test void compareMoneyFractionalNegativeDifference(){
        Money m = new Money(new BigDecimal(100), "dollars");
        Money n = new Money(new BigDecimal(100.50), "dollars");
        assertEquals(true,  m.compareTo(n) < 0);
    }
    @Test void compareMoneyFractionalPositiveDifference(){
        Money m = new Money(new BigDecimal(101), "dollars");
        Money n = new Money(new BigDecimal(100.50), "dollars");
        assertEquals(true,  m.compareTo(n) > 0);
    }
    @Test void hashSetMoney(){
        HashSet<Money> h = new HashSet<Money>();
        Money m = new Money(new BigDecimal(101), "dollars");
        h.add(m);
        Money n  = new Money(new BigDecimal(101.0), "dollars");
        h.add(n);
        assertTrue(h.size() == 1);

    }
}
